sudo: required

dist: trusty

addons:
  apt:
    update: true
    packages:
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-pictures
    - latex-xcolor
    - lmodern
    - dvipng
    - texlive-math-extra
    - pgf

script:
  - mkdir _build
  - xelatex -interaction=nonstopmode -halt-on-error -output-directory _build garciparedes-cv.tex

deploy:
  provider: releases
  file:
    - _build/garciparedes-cv.pdf
  skip_cleanup: true
  on:
    tags: true
