sudo: required

dist: trusty

addons:
  apt:
    packages:
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - latex-xcolor
      - lmodern
      - dvipng

script:
  - mkdir _build
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build garciparedes-cv.tex

deploy:
  provider: releases
  file:
    - _build/garciparedes-cv.pdf
  skip_cleanup: true
  on:
    tags: true
