sudo: required

dist: trusty

addons:
  apt:
    update: true
    packages:
    - texlive-full
    - biber
    - latex-xcolor
    - lmodern
    - dvipng
    - pgf

cache:
  apt: true


before_script:
  - tlmgr update --self --all

script:
  - mkdir _build
  - xelatex -interaction=nonstopmode -halt-on-error -output-directory _build garciparedes-cv.tex

deploy:
  provider: releases
  file:
    - _build/garciparedes-cv.pdf
  skip_cleanup: true
  on:
    tags: true
